---
- name: Create external-dns namespace
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: v1
    kind: Namespace
    metadata:
      name: external-dns
    EOF

- name: Install external-dns Helm chart via ArgoCD
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: external-dns
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: external-dns
        targetRevision: 8.3.12
        helm:
          values: |
            provider: gandi
            sources:
              - ingress
            domainFilters:
              - "{{ domain }}"
            extraEnvVars:
              - name: GANDI_PAT
                valueFrom:
                  secretKeyRef:
                    name: gandi-pat-secret
                    key: GANDI_PAT
      destination:
        server: https://kubernetes.default.svc
        namespace: external-dns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    EOF

- name: Create secret for GANDI_PAT
  shell: |
    kubectl create secret generic gandi-pat-secret \
      --namespace external-dns \
      --from-literal=GANDI_PAT="{{ gandi_pat }}" \
      --dry-run=client -o yaml | kubectl apply -f -