version: '3.8'

services:
  captain:
    image: ghcr.io/captain-corp/captain:latest
    container_name: captain
    environment:
      - CAPTAIN_SERVER_HOST=0.0.0.0
      - CAPTAIN_SERVER_PORT=8080
      - CAPTAIN_DB_PATH=/data/blog.db
      - CAPTAIN_STORAGE_PROVIDER=local
      - CAPTAIN_STORAGE_PATH=/data/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
